### ISSUE TITLE
GNU GCC & newlib version issue

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/rt-thread#1888]
In Linux environment, RT-Thread will have restrictions on version of GCC and newlib. For example, only a few versions of GNU Arm Embedded Toolchain are verified now:
GNU Arm Embedded Toolchain 5.4, 6. And not support GNU Arm Embedded Toolchain 7.

But for the new version, or the toolchains self builds, it does not support well.

**Comment by BernardXiong** [comment]
fix with #1964 except for pthreads.

**Comment by pinxue** [comment]
The newlib-pthread error still exists.

toolchain:
arm-none-eabi-binutils         @2.33.1         cross/arm-none-eabi-binutils
arm-none-eabi-gcc              @9.2.0          cross/arm-none-eabi-gcc
arm-none-eabi-gdb              @7.9            cross/arm-none-eabi-gdb

error message:
10:qemu-vexpress-a9 pinxue$ scons
scons: Reading SConscript files ...
b''
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
CC build/applications/lcd_init.o
CC build/applications/main.o
CC build/applications/mnt.o
CC build/drivers/board.o
CC build/drivers/drv_keyboard.o
CC build/drivers/drv_mouse.o
CC build/drivers/drv_sdio.o
CC build/drivers/drv_smc911x.o
CC build/drivers/drv_timer.o
CC build/drivers/secondary_cpu.o
CC build/drivers/serial.o
CXX build/kernel/components/cplusplus/Mutex.o
CXX build/kernel/components/cplusplus/Semaphore.o
CXX build/kernel/components/cplusplus/Thread.o
CXX build/kernel/components/cplusplus/crt.o
CC build/kernel/components/cplusplus/crt_init.o
CC build/kernel/components/dfs/filesystems/devfs/devfs.o
CC build/kernel/components/dfs/filesystems/elmfat/dfs_elm.o
CC build/kernel/components/dfs/filesystems/elmfat/ff.o
CC build/kernel/components/dfs/filesystems/elmfat/option/ccsbcs.o
CC build/kernel/components/dfs/filesystems/ramfs/dfs_ramfs.o
CC build/kernel/components/dfs/filesystems/romfs/dfs_romfs.o
CC build/kernel/components/dfs/filesystems/romfs/romfs.o
CC build/kernel/components/dfs/src/dfs.o
CC build/kernel/components/dfs/src/dfs_file.o
CC build/kernel/components/dfs/src/dfs_fs.o
CC build/kernel/components/dfs/src/dfs_posix.o
CC build/kernel/components/dfs/src/poll.o
CC build/kernel/components/dfs/src/select.o
CC build/kernel/components/drivers/i2c/i2c-bit-ops.o
CC build/kernel/components/drivers/i2c/i2c_core.o
CC build/kernel/components/drivers/i2c/i2c_dev.o
CC build/kernel/components/drivers/misc/pin.o
CC build/kernel/components/drivers/mtd/mtd_nand.o
CC build/kernel/components/drivers/mtd/mtd_nor.o
CC build/kernel/components/drivers/rtc/rtc.o
CC build/kernel/components/drivers/rtc/soft_rtc.o
CC build/kernel/components/drivers/sdio/block_dev.o
CC build/kernel/components/drivers/sdio/mmc.o
CC build/kernel/components/drivers/sdio/mmcsd_core.o
CC build/kernel/components/drivers/sdio/sd.o
CC build/kernel/components/drivers/sdio/sdio.o
CC build/kernel/components/drivers/serial/serial.o
CC build/kernel/components/drivers/spi/sfud/src/sfud.o
~rt-thread/components/drivers/spi/sfud/src/sfud.c: In function 'set_write_enabled':
~rt-thread/components/drivers/spi/sfud/src/sfud.c:900:77: warning: bitwise comparison always evaluates to false [-Wtautological-compare]
  900 |         } else if (!enabled && (register_status & SFUD_STATUS_REGISTER_WEL) == 1) {
      |                                                                             ^~
CC build/kernel/components/drivers/spi/sfud/src/sfud_sfdp.o
CC build/kernel/components/drivers/spi/spi_core.o
CC build/kernel/components/drivers/spi/spi_dev.o
CC build/kernel/components/drivers/spi/spi_flash_sfud.o
CC build/kernel/components/drivers/spi/spi_msd.o
CC build/kernel/components/drivers/src/completion.o
CC build/kernel/components/drivers/src/dataqueue.o
CC build/kernel/components/drivers/src/pipe.o
CC build/kernel/components/drivers/src/ringblk_buf.o
CC build/kernel/components/drivers/src/ringbuffer.o
CC build/kernel/components/drivers/src/waitqueue.o
CC build/kernel/components/drivers/src/workqueue.o
CC build/kernel/components/drivers/watchdog/watchdog.o
CC build/kernel/components/finsh/cmd.o
CC build/kernel/components/finsh/finsh_compiler.o
CC build/kernel/components/finsh/finsh_error.o
CC build/kernel/components/finsh/finsh_heap.o
CC build/kernel/components/finsh/finsh_init.o
CC build/kernel/components/finsh/finsh_node.o
CC build/kernel/components/finsh/finsh_ops.o
CC build/kernel/components/finsh/finsh_parser.o
CC build/kernel/components/finsh/finsh_token.o
CC build/kernel/components/finsh/finsh_var.o
CC build/kernel/components/finsh/finsh_vm.o
CC build/kernel/components/finsh/msh.o
CC build/kernel/components/finsh/msh_file.o
CC build/kernel/components/finsh/shell.o
CC build/kernel/components/libc/aio/posix_aio.o
CC build/kernel/components/libc/compilers/newlib/libc.o
In file included from /opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:23,
                 from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
~rt-thread/components/libc/pthreads/sched.h:19:5: error: expected identifier before numeric constant
   19 |     SCHED_OTHER = 0,
      |     ^~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:29: warning: "PTHREAD_CREATE_JOINABLE" redefined
   29 | #define PTHREAD_CREATE_JOINABLE     0x00
      |
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:47: note: this is the location of the previous definition
   47 | #define PTHREAD_CREATE_JOINABLE  1
      |
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:30: warning: "PTHREAD_CREATE_DETACHED" redefined
   30 | #define PTHREAD_CREATE_DETACHED     0x01
      |
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:46: note: this is the location of the previous definition
   46 | #define PTHREAD_CREATE_DETACHED 0
      |
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:32: warning: "PTHREAD_EXPLICIT_SCHED" redefined
   32 | #define PTHREAD_EXPLICIT_SCHED      0
      |
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:43: note: this is the location of the previous definition
   43 | #define PTHREAD_EXPLICIT_SCHED 2      /* set from provided attribute object */
      |
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:35:14: error: conflicting types for 'pthread_t'
   35 | typedef long pthread_t;
      |              ^~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:32:20: note: previous declaration of 'pthread_t' was here
   32 | typedef __uint32_t pthread_t;            /* identify a thread */
      |                    ^~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:36:14: error: conflicting types for 'pthread_condattr_t'
   36 | typedef long pthread_condattr_t;
      |              ^~~~~~~~~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:186:3: note: previous declaration of 'pthread_condattr_t' was here
  186 | } pthread_condattr_t;         /* a condition attribute object */
      |   ^~~~~~~~~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:38:14: error: conflicting types for 'pthread_mutexattr_t'
   38 | typedef long pthread_mutexattr_t;
      |              ^~~~~~~~~~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:169:3: note: previous declaration of 'pthread_mutexattr_t' was here
  169 | } pthread_mutexattr_t;
      |   ^~~~~~~~~~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:41:13: error: conflicting types for 'pthread_key_t'
   41 | typedef int pthread_key_t;
      |             ^~~~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:190:20: note: previous declaration of 'pthread_key_t' was here
  190 | typedef __uint32_t pthread_key_t;        /* thread-specific data keys */
      |                    ^~~~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:42:13: error: conflicting types for 'pthread_once_t'
   42 | typedef int pthread_once_t;
      |             ^~~~~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:195:3: note: previous declaration of 'pthread_once_t' was here
  195 | } pthread_once_t;       /* dynamic package initialization */
      |   ^~~~~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:79:8: error: redefinition of 'struct sched_param'
   79 | struct sched_param
      |        ^~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:23,
                 from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/sched.h:48:8: note: originally defined here
   48 | struct sched_param {
      |        ^~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:95:29: error: conflicting types for 'pthread_attr_t'
   95 | typedef struct pthread_attr pthread_attr_t;
      |                             ^~~~~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:75:3: note: previous declaration of 'pthread_attr_t' was here
   75 | } pthread_attr_t;
      |   ^~~~~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:102:30: error: conflicting types for 'pthread_mutex_t'
  102 | typedef struct pthread_mutex pthread_mutex_t;
      |                              ^~~~~~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:154:20: note: previous declaration of 'pthread_mutex_t' was here
  154 | typedef __uint32_t pthread_mutex_t;      /* identify a mutex */
      |                    ^~~~~~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:109:29: error: conflicting types for 'pthread_cond_t'
  109 | typedef struct pthread_cond pthread_cond_t;
      |                             ^~~~~~~~~~~~~~
In file included from /opt/local/arm-none-eabi/include/sys/types.h:239,
                 from /opt/local/arm-none-eabi/include/sys/signal.h:12,
                 from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/_pthreadtypes.h:176:20: note: previous declaration of 'pthread_cond_t' was here
  176 | typedef __uint32_t pthread_cond_t;       /* identify a condition variable */
      |                    ^~~~~~~~~~~~~~
In file included from ~rt-thread/components/libc/compilers/newlib/libc.c:19:
~rt-thread/components/libc/pthreads/pthread.h:191:5: error: conflicting types for 'pthread_kill'
  191 | int pthread_kill(pthread_t thread, int sig);
      |     ^~~~~~~~~~~~
In file included from ~rt-thread/include/libc/libc_signal.h:67,
                 from ~rt-thread/include/rtdef.h:466,
                 from ~rt-thread/include/rtthread.h:24,
                 from ~rt-thread/components/libc/compilers/newlib/libc.c:10:
/opt/local/arm-none-eabi/include/sys/signal.h:226:5: note: previous declaration of 'pthread_kill' was here
  226 | int pthread_kill (pthread_t, int);
      |     ^~~~~~~~~~~~
scons: *** [build/kernel/components/libc/compilers/newlib/libc.o] Error 1
scons: building terminated because of errors.

**Comment by Guozhanxin** [comment]
目前已支持 gcc10，这个issue可以关闭了

**Comment by wahaha02** [comment]
@Guozhanxin 您好。在RTT v3.1.4上，GCC版本从5.4.1升级到10.2.1后，也遇到这个问题。请问如何修复？
