### ISSUE TITLE
Issue: compiling error

### ISSUE THREAD

**Issue by jiejiezhang** [RT-Thread/rt-thread#3174]
你好，我按照官方文档操作配置ununtu下的环境：　https://www.rt-thread.org/document/site/application-note/setup/qemu/ubuntu/an0005-qemu-ubuntu/

最后出现如下错误，帮忙看一下是什么原因引起的，谢谢
![scons](https://user-images.githubusercontent.com/23076781/68081749-e0dc9480-fe4d-11e9-8f69-8f32e5cd51dd.png)

**Comment by a1012112796** [comment]
@jiejiezhang 您好，建议您在论坛上发。

**Comment by jiejiezhang** [comment]
好的，非常感谢这么快的回复

**Comment by BernardXiong** [comment]
It's caused by GCC version or GCC detection issue. 

Normally, there are two `fd_set` definitions, libc's or RT-Thread's. The scons will check which definition should be used and then generate cconfig.h file for compiling.

When you met this issue, you can:

1. Remove cconfig.h file manually or by `scons -c` command;

or 

2. Use old GNU GCC version (<= 6.x in ARM).

**Comment by jiejiezhang** [comment]
Thanks very much. Now it can work normally!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bernard Xiong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 晚上8:16
收件人:&nbsp;"RT-Thread/rt-thread"<rt-thread@noreply.github.com&gt;;
抄送:&nbsp;"1317674293@qq.com"<1317674293@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [RT-Thread/rt-thread] issue: compiling error (#3174)




It's caused by GCC version or GCC detection issue.
 
Normally, there are two fd_set definitions, libc's or RT-Thread's. The scons will check which definition should be used and then generate cconfig.h file for compiling.
 
When you met this issue, you can:
  
Remove cconfig.h file manually or by scons -c command;
  
or
  
Use old GNU GCC version (<= 6.x in ARM).
