### ISSUE TITLE
RT1170-EVK BSP 编译错误

### ISSUE THREAD

**Issue by xjy198903** [RT-Thread/rt-thread#6190]
RT1170-EVK在4.1.1版本中，编译失败，无论是keil或是IAR，都会找不到components\libc\compilers\common下的stdlib.c和ctime.c；增加CAN支持后，drv_can.c编译失败

**Comment by xjy198903** [comment]
另外，RT1170-EVK在rt-thread是否能实现多核通信，比如使用eRPC来进行RPMSG

**Comment by mysterywolf** [comment]
你重新生成工程了嘛？

**Comment by xjy198903** [comment]
> 你重新生成工程了嘛？
重新生成工程了，compilers那个问题没有了，不过CAN工程还是编译不过，需要手动修改源文件及SConscript

**Comment by thewon86** [comment]
> 

您好，我也有打算用 erpc ，做点儿东西。但是没找到在rtos上使用的教程

**Comment by xjy198903** [comment]
增加ETH支持时，drv_eth.c报错：
![rtthread添加ETH支持编译失败](https://user-images.githubusercontent.com/29084288/181147526-8f1b0b11-c517-47f0-8aa8-4b122b49674f.jpg)

**Comment by xjy198903** [comment]
> > 
> 
> 您好，我也有打算用 erpc ，做点儿东西。但是没找到在rtos上使用的教程

我在看能不能借用nxp官方的erpc的Demo

**Comment by mysterywolf** [comment]
目前1170还没有支持Can https://github.com/RT-Thread/rt-thread/blob/master/bsp/imxrt/imxrt1170-nxp-evk/README_zh.md

**Comment by xjy198903** [comment]
> 目前1170还没有支持Can https://github.com/RT-Thread/rt-thread/blob/master/bsp/imxrt/imxrt1170-nxp-evk/README_zh.md

文档里写的支持Ethernet，但实际编译都有问题：
![image](https://user-images.githubusercontent.com/29084288/181148452-8f7a0aaf-4919-426f-b435-5a9418411dda.png)

**Comment by andychen329** [comment]
@xinyigao @xinyigao11 看看哦

**Comment by xjy198903** [comment]
> @xinyigao @xinyigao11 看看哦
网络设备引脚也没配对，这个版本不应该称为release版本

**Comment by xinyigao** [comment]
好的

发件人: andychen329 ***@***.***>
发送时间: 2022年8月1日 9:27
收件人: RT-Thread/rt-thread ***@***.***>
抄送: Xinyi Gao ***@***.***>; Mention ***@***.***>
主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190)


Caution: EXT Email

@xinyigao<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxinyigao&data=05%7C01%7Cxinyi.gao%40nxp.com%7C523a4eece11b4990ca3508da735cf5bb%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637949140346529334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8n0bsJHG3FFq9J26212CIkJmSSZg83h3ab8thr7Vvjc%3D&reserved=0> @xinyigao11<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxinyigao11&data=05%7C01%7Cxinyi.gao%40nxp.com%7C523a4eece11b4990ca3508da735cf5bb%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637949140346529334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q20i545wW4sH1%2FlnWqP243GEBAHPW6Lqd1hkR5Wyq8I%3D&reserved=0> 看看哦

―

**Comment by xjy198903** [comment]
问下，RT1170的正式版大概什么时候能出？目前千兆网络不通，SDRAM初始化成功，但使用rt_malloc时，申请大于1M的空间，串口会卡住不动，无法再进行操作；单独使用rt_memheap_alloc可以申请1M的空间

**Comment by xinyigao** [comment]
1170目前支持100M ENET，enet_rst引脚为（GPIO6 ，12）在设置的时候需要注意，代码最近几天就会更新，至于您说的rt_malloc申请问题，需要具体分析，同时还要看下代码中分配的堆大小
发件人: xjy198903 ***@***.***>
发送时间: 2022年8月8日 16:36
收件人: RT-Thread/rt-thread ***@***.***>
抄送: Xinyi Gao ***@***.***>; Mention ***@***.***>
主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190)


Caution: EXT Email

问下，RT1170的正式版大概什么时候能出？目前千兆网络不通，SDRAM初始化成功，但使用rt_malloc时，申请大于1M的空间，串口会卡住不动，无法再进行操作；单独使用rt_memheap_alloc可以申请1M的空间

―

**Comment by xinyigao** [comment]
设备的引脚是在menuconfig中配置的，同时还要使能gpio模块才能正确初始化
发件人: xjy198903 ***@***.***>
发送时间: 2022年8月1日 9:37
收件人: RT-Thread/rt-thread ***@***.***>
抄送: Xinyi Gao ***@***.***>; Mention ***@***.***>
主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190)


Caution: EXT Email

@xinyigao<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxinyigao&data=05%7C01%7Cxinyi.gao%40nxp.com%7Cf95a46a3838a45629c1d08da735e4c6b%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637949146095155655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7CKweZWWNBD42U1TY0yGBHq%2F9aIRJN%2BPCsOWkrS2yP4%3D&reserved=0> @xinyigao11<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxinyigao11&data=05%7C01%7Cxinyi.gao%40nxp.com%7Cf95a46a3838a45629c1d08da735e4c6b%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637949146095155655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ltOtKDhPkB%2FxlM8lyC33MILrxPwEVKRbE4ys5bUZQQs%3D&reserved=0> 看看哦
网络设备引脚也没配对，这个版本不应该称为release版本

―

**Comment by xjy198903** [comment]
百兆的我编过了，禁用DCHP，使用默认IP 192.168.1.30，但是ping不通开发主机；我是在main函数中进行的rt_malloc的问题，发现不止是不能分配一兆。分布131072大小就会卡住，系统无法再进行操作

**Comment by xinyigao** [comment]
***@***.***

发件人: xjy198903 ***@***.***>
发送时间: 2022年8月8日 17:29
收件人: RT-Thread/rt-thread ***@***.***>
抄送: Xinyi Gao ***@***.***>; Mention ***@***.***>
主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190)


Caution: EXT Email

百兆的我编过了，禁用DCHP，使用默认IP 192.168.1.30，但是ping不通开发主机；我是在main函数中进行的rt_malloc的问题，发现不止是不能分配一兆。分布131072大小就会卡住，系统无法再进行操作

―

**Comment by xjy198903** [comment]
> ***@***.*** 发件人: xjy198903 ***@***.***> 发送时间: 2022年8月8日 17:29 收件人: RT-Thread/rt-thread ***@***.***> 抄送: Xinyi Gao ***@***.***>; Mention ***@***.***> 主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190) Caution: EXT Email 百兆的我编过了，禁用DCHP，使用默认IP 192.168.1.30，但是ping不通开发主机；我是在main函数中进行的rt_malloc的问题，发现不止是不能分配一兆。分布131072大小就会卡住，系统无法再进行操作 ― Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRT-Thread%2Frt-thread%2Fissues%2F6190%23issuecomment-1207885358&data=05%7C01%7Cxinyi.gao%40nxp.com%7C83d84ce8b4174f0a2c9c08da79207399%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637955477525508033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lN0gQR%2FTWk6ezzuDF0ZdQtA6MML39g2i1hbAnqyueZU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJU2SMBQLSTWIR7Y5VKMJF3VYDHOLANCNFSM54RCBTVQ&data=05%7C01%7Cxinyi.gao%40nxp.com%7C83d84ce8b4174f0a2c9c08da79207399%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637955477525508033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vNxmIl9%2FbeZqqzqWdnpfAKM38aNwxXcCsaIeV43%2BV2c%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***>

这是啥？

**Comment by xinyigao** [comment]
这边经过测试
“
#include <rtthread.h>
#include <rtdevice.h>
#include "drv_gpio.h"
char b_path[141072]={1};
int main(void)
{
#ifndef PHY_USING_KSZ8081
    while (1)
    {
         char *full_path;
          full_path = (char *)rt_malloc(141072);
rt_memcpy(full_path, b_path, 141072);
          rt_kprintf("test\r\n");
           rt_thread_mdelay(500);
    }
#endif
}
“
在main函数中添加rt_malloc，可以正常运行并打印信息
发件人: xjy198903 ***@***.***>
发送时间: 2022年8月8日 18:07
收件人: RT-Thread/rt-thread ***@***.***>
抄送: Xinyi Gao ***@***.***>; Mention ***@***.***>
主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190)


Caution: EXT Email

@.*** 发件人: xjy198903 @.> 发送时间: 2022年8月8日 17:29 收件人: RT-Thread/rt-thread @.> 抄送: Xinyi Gao @.>; Mention @.> 主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRT-Thread%2Frt-thread%2Fissues%2F6190&data=05%7C01%7Cxinyi.gao%40nxp.com%7C694411cc9ecd4bf82c7508da7925b4b4%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637955500098177809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZKhsVNA4vbAKNza5prQkomLGUhvZxBfCPhCu6Lcg5BQ%3D&reserved=0>) Caution: EXT Email 百兆的我编过了，禁用DCHP，使用默认IP 192.168.1.30，但是ping不通开发主机；我是在main函数中进行的rt_malloc的问题，发现不止是不能分配一兆。分布131072大小就会卡住，系统无法再进行操作 D Reply to this email directly, view it on GitHubhttps://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRT-Thread%2Frt-thread%2Fissues%2F6190%23issuecomment-1207885358&data=05%7C01%7Cxinyi.gao%40nxp.com%7C83d84ce8b4174f0a2c9c08da79207399%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637955477525508033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lN0gQR%2FTWk6ezzuDF0ZdQtA6MML39g2i1hbAnqyueZU%3D&reserved=0<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRT-Thread%2Frt-thread%2Fissues%2F6190%23issuecomment-1207885358&data=05%7C01%7Cxinyi.gao%40nxp.com%7C694411cc9ecd4bf82c7508da7925b4b4%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637955500098334047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Zk%2FICxbdrYn78xEsIOVY61%2Bey4RIjFPNip3wVlsKrBE%3D&reserved=0>, or unsubscribehttps://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJU2SMBQLSTWIR7Y5VKMJF3VYDHOLANCNFSM54RCBTVQ&data=05%7C01%7Cxinyi.gao%40nxp.com%7C83d84ce8b4174f0a2c9c08da79207399%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637955477525508033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vNxmIl9%2FbeZqqzqWdnpfAKM38aNwxXcCsaIeV43%2BV2c%3D&reserved=0<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJU2SMBQLSTWIR7Y5VKMJF3VYDHOLANCNFSM54RCBTVQ&data=05%7C01%7Cxinyi.gao%40nxp.com%7C694411cc9ecd4bf82c7508da7925b4b4%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637955500098334047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WAXmG2F6ZBXw2eGmkglKZ0a3vtKJZGNIf7Z6QHFi7io%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: @.***>

这是啥？

―

**Comment by xjy198903** [comment]
加了SDRAM的支持吗？

**Comment by mysterywolf** [comment]
@xinyigao 感谢帮忙测试~

**Comment by xinyigao** [comment]
如果您是想使用0x80 开头的地址，在keil中已经实现可以直接使用（不用配置sdram）,如果想在iar中直接使用，可以修改link.icf文件（直接参考官方sdk中带sdram配置的.icf 文件）

发件人: xjy198903 ***@***.***>
发送时间: 2022年8月8日 18:16
收件人: RT-Thread/rt-thread ***@***.***>
抄送: Xinyi Gao ***@***.***>; Mention ***@***.***>
主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190)


Caution: EXT Email

加了SDRAM的支持吗？

―

**Comment by xjy198903** [comment]
> 

麻烦确认下目前已发布的1170bsp百兆网络驱动部分，在不修改源码的情况下，编译都无法通过，我在手动修改编译错误的地方后，镜像可以生成，但网络不通，测试方法是ping主机，双向互ping均不通

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/6244 这有一个新的PR 等合并之后你再试一下

**Comment by xjy198903** [comment]
> #6244 这有一个新的PR 等合并之后你再试一下

已参考并修改，编译测试一把过，感谢！现在要琢磨千兆网络了，这个才是我真正需要的

**Comment by xjy198903** [comment]
NXP官方有支持千兆phy(rtl8211f)的计划吗？

**Comment by xinyigao** [comment]
这边经过测试添加sdram后也是支持的
您要不下是内存越界还是其他原因造成的？

发件人: xjy198903 ***@***.***>
发送时间: 2022年8月8日 18:16
收件人: RT-Thread/rt-thread ***@***.***>
抄送: Xinyi Gao ***@***.***>; Mention ***@***.***>
主题: [EXT] Re: [RT-Thread/rt-thread] RT1170-EVK BSP 编译错误 (Issue #6190)


Caution: EXT Email

加了SDRAM的支持吗？

―

**Comment by xjy198903** [comment]
这个问题已经处理完了
